### ISSUE TITLE
I found that my serial port could not receive data normally after working for a period of time

### ISSUE THREAD

**Issue by guaicaiboshi** [jcurl/SerialPortStream#100]
I found that my serial port could not receive data normally after working for a period of time.
Working for two hours or so is unacceptable.

**Comment by jcurl** [comment]
This problem doesn't contain any information that can be used for analysis (what does "could not receive data normally actually mean?). I've used it on other projects for a long period of time, receiving data from remote targets and it works as I'd expect.

Closing for a lack of information. 

If you can provide a more specific case of what the problem you're seeing (specify the inputs to your application, the outputs), I can investigate it further. For a good bug report, see the Wiki. a good example is #104
