### ISSUE TITLE
Not able to install NuGet for Xamarin.Forms

### ISSUE THREAD

**Issue by agehrin50** [jcurl/SerialPortStream#106]
When trying to install the NuGet within a project, the following error occurs: `Could not install package 'Microsoft.Win32.Registry 4.3.0'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v9.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author`. The project is using Xamarin.Forms version 4.4. We were looking to use this NuGet because of its ability to be cross-compatible since our project has mobile support; we are not using this NuGet within the mobile side of our project, but the mobile side ends up referencing the NuGet with how our project is setup.

**Comment by jcurl** [comment]
I can't help you there with Android. It's tested on Mono for Linux, so based on the NetFX desktop. You could try taking the sources and build yourself.

There's no plans to support this platform.
