### ISSUE TITLE
GetPortDescriptions returns incomplete information on WIN10

### ISSUE THREAD

**Issue by wheregone** [jcurl/SerialPortStream#111]
Hi,

It seems that USB ports only return empty string.

COM11  :
COM12  : CDC UART  
COM17  :

---
Ref: https://stackoverflow.com/questions/2837985/getting-serial-port-information

**Comment by jcurl** [comment]
It depends on the driver, and what that driver causes to be placed in the registry. I'm assuming you mean Windows. You'd want to look at WinNativeSerial.cs that has the implementation.
