### ISSUE TITLE
Caching of the modem status

### ISSUE THREAD

**Issue by galdenny** [jcurl/SerialPortStream#113]
I am considering to move to this implementation of the serial port in my project. 
For a specific port I need to check the modem status every 50 ms and evaluate the CTS, DSR, RING and CD/RLSD values.
Till now I have a custom c++ dll, that solves my problem, but any time I want to communicate over this port I need to close that and switch back to the normal SerialPort from .Net. I was very happy to see that SerialPortStream can deliver all the signals I described above. The only thing is, that the modem status will be asked every time for those. Given the frequency of the checks, it adds an overhead about 2-3% CPU with my i7. So I was asking, if it would be possible to cache the value of the modem status for a short time, or propagate it to the "surface" so all those signals could be evaluated by only one query.

Thank you in advance.

**Comment by jcurl** [comment]
No caching is done. If you request it, it goes directly to the underlying Operating System and returns the result. The library makes no assumptions about why you would to poll and at what interval.
