### ISSUE TITLE
ReadBufferSize changes when Serialportstream is open

### ISSUE THREAD

**Issue by gwenroyakkers** [jcurl/SerialPortStream#121]
I set the readbuffer before opening the port. (version 2.3.1)

```
_serialStream = new SerialPortStream();
_serialStream.ReadBufferSize = 16384;
```

After a few minutes my parser gets an error on an Array copy method....
When this happens the debugger in VisualStudio shows that the _serialStream.ReadBufferSize has magically become 32768 bytes...
The stream was open the whole time, and I only set the size in my code once.

Does anyone have an idea how this is possible?

With the previous version of the SerialPortStream NuGet package It was working... (or the latest windows 10 update is to blame)

Thanks

**Comment by jcurl** [comment]
Glad you solved your problem! Have a nice day.
