### ISSUE TITLE
ReadAsync/WriteAsync don't appear in ISerialPortStream (but they are in SerialPortStream)

### ISSUE THREAD

**Issue by Macaddict42** [jcurl/SerialPortStream#124]
For some reason I'm not seeing ReadAsync/WriteAsync anymore in the ISerialPortStream interface when using v2.3.1. Was this an accidental change or intentional?

**Comment by jcurl** [comment]
Does this commit fix your problem?

https://github.com/jcurl/SerialPortStream/commit/1d417a4c532420dc2622f2a523d18b6f6762ee83

**Comment by jcurl** [comment]
Assuming resolved, closing.
