### ISSUE TITLE
Support VS 2017 Net Standard / Net Core Project Types

### ISSUE THREAD

**Issue by SProst** [jcurl/SerialPortStream#20]
Currently the Net Standard 1.5 project type is the old json based project type. Is there a roadmap to update to the standard xml .csproj type that Microsoft added in VS 2017? 

Are there any plans to transition from packages.config and move to PackageReference?

**Comment by jcurl** [comment]
I have no plans to make this change, but you're more than welcome to propose a pull request. I need to make sure that it remains buildable using the build.bat script.
