### ISSUE TITLE
Thread Names on Linux

### ISSUE THREAD

**Issue by splitice** [jcurl/SerialPortStream#24]
On linux the thread names for the UnixNativeSerial threads are too long to be of any use. As a result the two threads are indistinguishable.

Perhaps shorten the prefix to "UNS"

**Comment by jcurl** [comment]
I assume you mean these two:
```
m_MonitorThread.Name = "UnixNativeSerial::Monitor_" + m_Name
m_PinThread.Name = "UnixNativeSerial::Pin_" + m_Name;
```

Have I missed any?

**Comment by splitice** [comment]
Yes, and those are the two I am aware of.

**Comment by jcurl** [comment]
Done. Pushed to v2.x.
