### ISSUE TITLE
DiscardInBuffer

### ISSUE THREAD

**Issue by MatejZem** [jcurl/SerialPortStream#26]
Hello,
First of all thumbs up for the good work.
Second I got an 
```
Unhandled exception System.NotImplementedException in mscorlib
System.NotImplementedException
The method or operation is not implemented.
```
when using the method DiscardInBuffer with Mono on Linux.
I have run some tests and found out that this method also didn't work before the update.

**Comment by jcurl** [comment]
Looks like it works in Windows, but was never implemented for Linux. I'll investigate.

**Comment by jcurl** [comment]
I've provided a fix if you can test on the branch "bugfix/discard". When you confirm it works as expected, please let me know and I'll merge to v2.x

**Comment by MatejZem** [comment]
Thank you for your quick response.
But how do I test it out with my project in Visual Studio? I don't have any dll to reference to.
I had build the .so files for Linux.

Sorry for my lack of knowledge.

**Comment by jcurl** [comment]
Hi, no worries. There were no changes to libnserial.so, only to the sources. If you need, I can build for you a test nuget package.

**Comment by MatejZem** [comment]
Please build a test nuget package. I will appreciate it alot.

**Comment by jcurl** [comment]
The NUGET packages are installed. I usually push the version with symbols to NuGet, so rename that file and put in your path that NuGet can upgrade to within the MonoIDE.

[serialportstream.2.1.2-rc-1-discard.zip](https://github.com/jcurl/SerialPortStream/files/984497/serialportstream.2.1.2-rc-1-discard.zip)

**Comment by MatejZem** [comment]
Thank you very much! Is working! 
I had installed package with symbols and for now it is working. Buffer is emptied.
I'm continuously working with Mono on Linux and your Serial Port communication and I will report more bugs, if I may found some.

**Comment by jcurl** [comment]
Please do report any issues you find. I'm closing this as you tested the commit id ba916671016c92ad1e143257fb7b98df755c2180 which is now in the v2.x branch.
