### ISSUE TITLE
symbol lookup error:  ~/bin/usr/local/lib/libnserial.so.1: undefined symbol: pthread_once

### ISSUE THREAD

**Issue by fanikram** [jcurl/SerialPortStream#53]
Hello
I first compiled the support library libnserial.so for yokto-linux. (With Crosscompelling). I early install cmake in my Host.
After cloning the repository, I executed the following:
$ git clone https://github.com/jcurl/serialportstream.git
$ cd serialportstream/dll/serialunix
$ ./build.sh

 
After I started my programs I get the following errors:
./dotnet: symbol lookup error:  path/bin/usr/local/lib/libnserial.so.1: undefined symbol: pthread_once
how can I solve this?

**Comment by jcurl** [comment]
If you're using a cross compiler on the command line, you'll have to read CMake documentation on how to provide the options and compiler details needed. Alternatively, you'd have to read on Yocto on how to create a bitbake recipe and integrate into your meta layer.

Both these topics are out of scope for the SerialPortStream, as it is a question for either CMake itself, or Yocto.
