### ISSUE TITLE
Implement System.IO.Pipelines

### ISSUE THREAD

**Issue by tedvanderveen** [jcurl/SerialPortStream#65]
Looks like the recently added System.IO.Pipelines namespace is a very good fit for serial port I/O processes. Are you planning on deploying it for this project?
https://blogs.msdn.microsoft.com/dotnet/2018/07/09/system-io-pipelines-high-performance-io-in-net/
https://www.nuget.org/packages/System.IO.Pipelines/
The Package has support for .NetStardard 1.3+ / .Net 4.6+ / .Net Core 2.0+

**Comment by jcurl** [comment]
At this time, I'm not planning to use System.IO.Pipelines. I still need the software to target .NET 4.0 and pipelines would be a refactoring that I don't have time for at the moment.
