### ISSUE TITLE
Stable driver  PL-2303?

### ISSUE THREAD

**Issue by infonoahy** [jcurl/SerialPortStream#66]
Hi,
I am sorry for posting this as an issue, however I did not really know what else to do.

I am the owner of a 2001 Veyboard, a chord keyboard. And this keyboard uses a serial port. Therefore, I have bought a serial USB conversion cable from Swedish Clas Ohlson. It uses a (real?) PL-2303 RA chip and includes a driver DVD. I have tried the driver DVD as well as the latest driver from Prolific's website. It is not very stable. I believe this is a driver issue, as I tried the cable and Veyboard on a 32-bit Windows 7 computer which automatically installed the 2.0.0.19 version driver which woked quite well, actually. But I have not been able to find this driver for 64-bit.

However, I found this Github repo and I am not really sure what this is. But, if you have any stable driver for PL-2303 that I can try, please let me know. ;)
(for Windows 10 OR Windows 7 64-bit)

Kind regards,
Noah

**Comment by jcurl** [comment]
No problems. First, the SerialPortStream is a library for .NET that works on Windows and Linux, but it is  *not* a driver. It's just an abstraction and cannot help you with your problem.

My experience with Prolific isn't the best on Windows - it's better on Linux (the in built drivers). Try the prolific site direct and install the driver from there http://www.prolific.com.tw/US/ShowProduct.aspx?p_id=225&pcid=41 if it helps.

If you want better software compatibility and reliability overall, I use FTDI converters.
