### ISSUE TITLE
RPI3 CPU 180%

### ISSUE THREAD

**Issue by JTrotta** [jcurl/SerialPortStream#68]
Just testing the library with 2 port. The only ports opening consume 180%, opening 1 port 90%.
Version 2.1.4.0, and mono 5.14.0.177 
Any hints?

EDIT: I recompiled the library without the pin PinChangeThread, and cpu is nomal now
`            //try {
            //    m_MonitorPins = true;
            //    m_PinThread = new Thread(new ThreadStart(PinChangeThread));
            //    m_PinThread.Name = "NSerPin_" + m_Name;
            //    m_PinThread.IsBackground = true;
            //    m_PinThread.Start();
            //} catch {
            //    m_PinThread = null;
            //    m_MonitorPins = false;
            //    throw;
            //}`

**Comment by jcurl** [comment]
Yes, it's likely a duplicate to this: https://github.com/jcurl/SerialPortStream/issues/22. I don't have an RPI3 to debug, as the fix itself must be in the libnserial library. I'll be closing this as a duplicate to that ticket. If you're capable, you can provide a patch, which I can integrate (and perhaps modify), after you test.
