### ISSUE TITLE
MacOS with Mono/Xamarin compatibility

### ISSUE THREAD

**Issue by pdulapalli** [jcurl/SerialPortStream#71]
Hello,

I was wondering is this compatible with macOS using Xamarin? If so, how do the build/usage steps differ from Linux?

**Comment by jcurl** [comment]
Hello, i have no Mac to test with, but as the tools are open source, it shouldn't really differ between Linux and Mac. The .NET sources should run using Mono, as it queries the environment and code there checks for either Windows or a Unix Like enviornment that includes the Mac.

What does differ slightly are the dependencies on the system during CMake. If you find a problem, please report it. I won't however be able to fix and test, so a pull request would be require. Have a look at the current issues, there was one item with the Mac, if you could confirm or deny.
