### ISSUE TITLE
How to check if there is no incomming data from external device

### ISSUE THREAD

**Issue by cvq** [jcurl/SerialPortStream#72]
Hi Everyone,
Thank you Jcurl for your software.
I want to check if there is no incomming data from external device connected to my PC via Serial port. (for example, when the external device is turn off).
Please help.
Thank you.

**Comment by jcurl** [comment]
It depends on the wires you have. Modems used extra signals, which if wired, can help you. Particularly the RI (Ring Indicator), or the CD (Carrier Detect). Additionally, if you have flow control, you can use the RTS/CTS or DTR/DTS signals to know if the remote device can receive data.

**Comment by cvq** [comment]
Thank you Jcurl.
