### ISSUE TITLE
Release notes document

### ISSUE THREAD

**Issue by vadrianc** [jcurl/SerialPortStream#82]
The current version is 2.2.0, but the existing **Changes.txt** contains a description of the 2.0.0 release. 

Having a **Release Notes.md** document where each release changes are documented could prove useful for anyone intending to upgrade the version of the library.

**Comment by jcurl** [comment]
OK, the documentation is out of date, but there are current release notes by each release using the "releases" tag from GitHub.

**Comment by vadrianc** [comment]
Ok, I missed that link. I'll close this ticket.

**Comment by jcurl** [comment]
I'm going to reopen it, so I can update the release notes, although it's not a high prio.

**Comment by jcurl** [comment]
Released in v2.2.1 on NuGet
