### ISSUE TITLE
Write large data(~128kB) will cause out buffer wrap around

### ISSUE THREAD

**Issue by Kurapikov** [jcurl/SerialPortStream#9]
Hi Jason,

I tested the 2.0.0 release, and found a weird bug.

I need to write about 1MB data through UART. Each time I write 256 bytes (as a page) and wait for slave ack. When about 128kB data is writed, slave received the first page I've wrote.

I tried to flush and discard out buffer after every 256 bytes write, and this problem is resolved.

I have no time to read through the code to analysis what happened.

I can do more test if you need.

Regards.

**Comment by jcurl** [comment]
Can you please provide a small test program that recreates the issue? I'm particularly interested in the drivers and chipset of the serial port, how you initialise the serial port. Then please enable debugging to a file and send me the logs (see http://serialportstream.codeplex.com/wikipage?title=TraceSwitch%20Settings&referringTitle=Documentation). This page might also help (http://serialportstream.codeplex.com/wikipage?title=Providing%20Debug%20Information&referringTitle=Documentation)

**Comment by jcurl** [comment]
As I've not heard any response, and I've not seen this issue in the unit test cases that do similar work, I'm closing.
